services:
  mysql:
    image: mysql:8.0
    container_name: ounce-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "Mickey51799@@"
      MYSQL_DATABASE: Ounce
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ounce-mysql-data:/var/lib/mysql

volumes:
  ounce-mysql-data:
