services:
  ounce-db:
    image: mysql:8.0
    container_name: ounce-db
    environment:
      MYSQL_ROOT_PASSWORD: Mickey51799@@
      MYSQL_DATABASE: Ounce
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pMickey51799@@"]
      interval: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  app-blue:
    image: hyejun02/ounce-api:latest
    container_name: app-blue
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://ounce-db:3306/Ounce?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mickey51799@@
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      DB_HOST: ounce-db
      JWT_SECRET: ${JWT_SECRET}

    depends_on:
      ounce-db:
        condition: service_healthy
    restart: always

  app-green:
    image: hyejun02/ounce-api:latest
    container_name: app-green
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://ounce-db:3306/Ounce?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mickey51799@@
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      DB_HOST: ounce-db
    depends_on:
      ounce-db:
        condition: service_healthy
    restart: always

  nginx:
    image: nginx:alpine
    container_name: ounce-nginx
    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always

volumes:
  db_data:
