spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  frontend-url: "https://ouncefresh.com/"
  cookie-secure: true

server:
  forward-headers-strategy: framework

search:
  engine: jpa

management:
  health:
    elasticsearch:
      enabled: false


  jpa:
    # 사용할 데이터베이스의 방언(Dialect) 설정
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # 엔티티 변경 시 테이블 스키마 자동 수정 전략
      # 개발 단계: update 또는 create, 운영 단계: none 또는 validate 권장
      ddl-auto: validate