

search:
  engine: elasticsearch

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    max-connections: 8192

spring:

# kafka 설정 정보
#  kafka:
#    bootstrap-servers: 54.180.210.154:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer


  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 3s
    socket-timeout: 10s
  thymeleaf:
    cache: false
  jwt:
    secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
    expiration_time: 1800000 # 30분
    refresh_expiration_time: 1209600000 # 14일
  application:
    name: Ounce

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "718802132738-rpslfjbp931c64nu48tfealgtssafhcc.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - profile
              - email
    user:
      name: user
      password: hj

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/Ounce?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Mickey51799@@

  jpa:
    # 사용할 데이터베이스의 방언(Dialect) 설정
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        # 출력되는 SQL문을 보기 좋게 포맷팅
        format_sql: true
        # SQL 주석(Comment) 표시
        use_sql_comments: true
    open-in-view: false

kind: Application

app:
  frontend-url: "http://localhost:8081/"
  cookie-secure: false

#server:
#  forward-headers-strategy: framework