events { worker_connections 1024; }

http {
    # 도커 컨테이너 이름을 찾기 위한 설정
    resolver 127.0.0.11 valid=5s;

    server {
        # 사용자는 무조건 80번 포트(기본 HTTP)로 접속합니다.
        listen 80;

        location / {
            # 아래 파일에서 현재 떠있는 서버($service_url)가 app-blue인지 app-green인지 읽어옵니다.
            include /etc/nginx/conf.d/service-env.inc;

            # 🌟 여기가 핵심 리버스 프록시 설정! 🌟
            # 사용자의 요청을 8080 또는 8081 포트로 몰래 넘겨줍니다.
            proxy_pass http://$service_url;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}